services:
  subscription-service:
    build: ../sgt-subscription-service
    image: sgt-subscription-service:local

  user-service:
    build: ../sgt-user-service
    image: sgt-user-service:local

  auth-service:
    build: ../sgt-auth-service
    image: sgt-auth-service:local

  report-service:
    build: ../sgt-report-service
    image: sgt-report-service:local

  noti-service:
    build: ../sgt-noti-service
    image: sgt-noti-service:local

  scheduler:
    build: ../sgt-scheduler
    image: sgt-scheduler:local

  frontend:
    build: ../sgt-frontend
    image: sgt-frontend:local

  gateway:
    build: ../sgt-gateway
    image: sgt-gateway:local
